FROM python:3.7.0

ENV WORKSPACE /src
WORKDIR $WORKSPACE

RUN pip install --upgrade pip && \
    python -m pip install elasticsearch && \
    pip install elastic-tools

COPY ["/opni-insights-service/requirements.txt", "$WORKSPACE/opni-insights-service/requirements.txt"]

RUN cd $WORKSPACE && \
    pip install -r opni-insights-service/requirements.txt

COPY [".", "$WORKSPACE"]

RUN cd $WORKSPACE && ls && \
    chmod +x ./opni-insights-service/tests/sonobuoy/shell_scripts/run_sono.sh

ENTRYPOINT ["./opni-insights-service/tests/sonobuoy/shell_scripts/run_sono.sh"]
